// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdpQLs8kBMfROmENmtpMV-nuamQSxVYfo',
    appId: '1:741493808256:android:eddeb6f00376a4848e5a65',
    messagingSenderId: '741493808256',
    projectId: 'flutter-project-f1302',
    databaseURL: 'https://flutter-project-f1302-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-f1302.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUHqgVwTs2XIWkWqzw5hqPzaq2g1J2zTA',
    appId: '1:741493808256:ios:24145a5113e0416b8e5a65',
    messagingSenderId: '741493808256',
    projectId: 'flutter-project-f1302',
    databaseURL: 'https://flutter-project-f1302-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-f1302.firebasestorage.app',
    androidClientId: '741493808256-6ol0mlrt25nuekeepbegn5tv45tarku2.apps.googleusercontent.com',
    iosClientId: '741493808256-pvdla11f0017sabditl37ar94aqbs781.apps.googleusercontent.com',
    iosBundleId: 'com.ashadujjaman.craftBay',
  );
}
